version: '3.4'

services:

  django:
    ports:
      - "8000:8000"
    command: /start
    depends_on:
      - db
      - redis

  db:
    image: mariadb
    restart: always
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    environment:
      MYSQL_DATABASE: "simicrofin_jdgp"
      MYSQL_USER: "evillanueva"
      MYSQL_PASSWORD: "evillanueva"
      MYSQL_ROOT_PASSWORD: "docker-root"


  redis:
    image: redis:5

